version: "3"
services:
    mysql:
        image: "mysql:8"
        volumes:
            - ~/data/mysql_8:/var/lib/mysql
        environment:
            - "MYSQL_ROOT_PASSWORD=123456"
        ports:
            - "3307:3306"